# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jobpostingadvisor

on:
  push:
    branches:
      - Version_alpha
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_24ec5ace5a5c4d349f4eb1f1ee14dd87 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_08303a44c4e24e24949f208b2c58b141 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_24ec5ace5a5c4d349f4eb1f1ee14dd87 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jobpostingadvisor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9c50104c545b438b9c02400ea4a6200c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_24ec5ace5a5c4d349f4eb1f1ee14dd87 }}/appsvc/staticsite:${{ github.sha }}'